### ISSUE TITLE
Add price to subscription

### ISSUE THREAD

**Issue by jakeperrin** [Prospress/woocommerce-subscribe-to-all-the-things#14] opened 2016-01-14 21:27 UTC
It would be nice to change the price for each subscription you add.

**Comment by seb86** [comment] 2016-01-18 02:57
@jakeperrin Read [this discussion](https://github.com/Prospress/woocommerce-subscribe-to-all-the-things/pull/13) for my pull request.

**Comment by franticpsyx** [comment] 2016-01-21 07:38
Duplicate of https://github.com/Prospress/woocommerce-subscribe-to-all-the-things/pull/13 - closing

**Closed by franticpsyx** 2016-01-21 07:38 UTC
